{
  target: {
    RequestScopeIdentifier: {
      ScopeId: Guid_1
    },
    EventHandlers: [
      {
        ServiceScopeId: Guid_2,
        WorkerStatus: Faulted,
        IsDisposed: true
      },
      {
        ServiceScopeId: Guid_2,
        WorkerStatus: Faulted,
        IsDisposed: true
      },
      {
        ServiceScopeId: Guid_2,
        WorkerStatus: Done,
        IsDisposed: true
      },
      {
        ServiceScopeId: Guid_2,
        WorkerStatus: Done,
        IsDisposed: true
      }
    ],
    MockTaskRunner: [
      {
        Method: TaskRunner.WhenAll(IEnumerable<Task> tasks),
        Arguments: [
          [
            {
              Status: WaitingForActivation
            },
            {
              Status: WaitingForActivation
            },
            {
              Status: WaitingForActivation
            },
            {
              Status: WaitingForActivation
            }
          ]
        ],
        ReturnValue: {
          Status: RanToCompletion
        }
      }
    ]
  },
  logs: [
    {
      Error: An exception was thrown while executing Reprise.UnitTests.Features.Events.EventBusTests.MockEventHandler.,
      Category: EventBus,
      State: [
        {
          EventHandlerType: Reprise.UnitTests.Features.Events.EventBusTests.MockEventHandler
        },
        {
          {OriginalFormat}: An exception was thrown while executing {EventHandlerType}.
        }
      ],
      Exception: {
        Type: Exception,
        Message: Test message
      }
    },
    {
      Error: An exception was thrown while executing Reprise.UnitTests.Features.Events.EventBusTests.MockEventHandler.,
      Category: EventBus,
      State: [
        {
          EventHandlerType: Reprise.UnitTests.Features.Events.EventBusTests.MockEventHandler
        },
        {
          {OriginalFormat}: An exception was thrown while executing {EventHandlerType}.
        }
      ],
      Exception: {
        Type: Exception,
        Message: Test message
      }
    }
  ]
}